# Project: w2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = w2/新文件5.o w2/新文件6.o
LINKOBJ  = w2/新文件5.o w2/新文件6.o
LIBS     = -L"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/lib" -L"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/include" -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/karta/Downloads/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = w2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

w2/新文件5.o: w2/新文件5.c
	$(CC) -c w2/新文件5.c -o w2/新文件5.o $(CFLAGS)

w2/新文件6.o: w2/新文件6.c
	$(CC) -c w2/新文件6.c -o w2/新文件6.o $(CFLAGS)
